---
name: Build RPM

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: rpmbuild
        uses: robertdebock/rpmbuild-action@1.0.0
